#pragma once
#include <string>

using namespace std;

enum Attribute
{
    PROCEDURE_ATTRIBUTE = 0,
    STMT_ATTRIBUTE,
    ASSIGN_ATTRIBUTE,
    CALL_STMT_ATTRIBUTE,
    CALL_PROC_ATTRIBUTE,
    WHILE_ATTRIBUTE,
    IF_ATTRIBUTE,
    VARIABLE_ATTRIBUTE,
    CONSTANT_ATTRIBUTE,
    INTEGER_ATTRIBUTE,
    IDENT_WITH_QUOTES_ATTRIBUTE,
    PROG_LINE_ATTRIBUTE
};
