#pragma once

typedef const int ENTITY;

ENTITY STMT = 0;
ENTITY ASSIGN = 1;
ENTITY WHILE = 2;
ENTITY IF = 3;
ENTITY PROG_LINE = 4;
ENTITY CALL = 5;
ENTITY PROCEDURE = 6;
ENTITY VARIABLE = 7;
ENTITY INTEGER = 8;
ENTITY UNDERSCORE = 9;
ENTITY IDENT_WITHQUOTES = 10;
ENTITY EXPRESSION_SPEC = 11;
ENTITY CONSTANT = 12;
ENTITY STMTLIST = 13;